GET http://localhost:3000/api/heroes

### 

GET http://localhost:3000/api/heroes/3

###

POST http://localhost:3000/api/heroes
Content-Type: application/json

{
    "name": "Axe",
    "attribute": "Strength",
    "role": "Tank"
}

###

DELETE http://localhost:3000/api/heroes/7

###

PUT http://localhost:3000/api/heroes/3
Content-Type: application/json

{
    "name": "Pudge",
    "attribute": "Strength",
    "role": "Tank"
}